# Generated by Django 4.2 on 2023-04-19 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0004_alter_aluno_celular'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='email',
            field=models.EmailField(default='blz', max_length=30),
        ),
    ]
