# Generated by Django 4.2 on 2023-04-19 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0005_aluno_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='email',
            field=models.EmailField(max_length=30),
        ),
    ]
