# Generated by Django 4.2 on 2023-04-19 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0006_alter_aluno_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='data_nascimento',
        ),
    ]
