# Generated by Django 4.2 on 2023-04-20 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0007_remove_aluno_data_nascimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='matriculado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Matricula_matriculado', to='escola.aluno'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Aluno_aluno', to='escola.aluno'),
        ),
    ]
