# Generated by Django 4.2 on 2023-04-20 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0008_matricula_matriculado_alter_matricula_aluno'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='matriculado',
            field=models.IntegerField(null=True),
        ),
    ]
