# Generated by Django 4.2 on 2023-04-20 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0010_remove_aluno_matriculado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='matriculado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='escola.aluno'),
        ),
    ]
