# Generated by Django 4.2 on 2023-04-21 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0011_alter_matricula_matriculado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matricula',
            name='matriculado',
        ),
        migrations.AddField(
            model_name='aluno',
            name='foto',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escola.aluno'),
        ),
    ]
