# Generated by Django 4.2 on 2023-04-25 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0012_remove_matricula_matriculado_aluno_foto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='exibe',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
